### ISSUE TITLE
coverage badge does not update after running command

### ISSUE THREAD

**Issue by ishaileshmishra** [jack-r-warren/remove_from_coverage#1]
coverage percentage increases running below commands but 
```
remove_from_coverage -f coverage/lcov.info -r '.g.dart$'
pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.g.dart$'
```
coverage badge does not update
`coverage badge icon also should be regenerated with updated coverage percentage.
`

**Comment by jack-r-warren** [comment]
Sorry for not keeping up with this repo -- I suspect this is an issue of not committing the changed `lcov` file. If this is still an issue feel free ping here again.
