### ISSUE TITLE
Example doesn't work on Windows due to single quotes  [fix]

### ISSUE THREAD

**Issue by akiller** [jack-r-warren/remove_from_coverage#13]
Hi,

This is more of a comment to help someone else out who finds this. Whether you want to update the README with a notice is up to you.

I couldn't get the replacement working on Windows. After playing around with the source and being very confused I realised (having forgot!) that it was due to the single quotes in the example and how the Windows command line deals with them (it treats them as text, not as a quote).

E.g., if we use -r 'regex_pattern' then the literal pattern that gets set from (args['remove'] as List<String>) is _'regex_pattern'_. It may not be obvious, but the single quotes are part of the search pattern it's looking for, which is wrong.

If we use -r "regex_pattern" then the pattern becomes just _regex_pattern_ - no quotes, and the tool works great.

Thanks

**Comment by jack-r-warren** [comment]
Good call, sorry this repo is kinda dead -- I have GitHub notifications off for work reasons and I didn't realize anyone was using this...
