### ISSUE TITLE
Exclude folder and subfolders feature.

### ISSUE THREAD

**Issue by xamantra** [jack-r-warren/remove_from_coverage#3]
I'm wondering if excluding an entire folder and it's sub-folders is possible.

**Reason:** Testing the widgets is really a pain in flutter. Especially when I change my UI tree/structure almost every day when I come up with new design layouts. When that happens, I need to revise my widget tests again. So with this, excluding an entire folder like `lib/src/widgets/` for the time being would be helpful. So that the vs code extension I'm using won't highlight thousands of widget code lines as *untested* in linter which is very annoying.

I only want to prioritize testing my logic and model data. 100% code coverage for them. And when the time comes that UI layouts won't change anymore, I'll be ready to write widget tests for them and include them back in the coverage.

PS: I still haven't browsed the source code of this project. But I have a feeling it is possible. Might try to fork this soon.

**Comment by furaiev** [comment]
` -r '.g.dart|.freezed.dart$|\binterfaces\b(?!.*bloc)'  && genhtml -o coverage coverage/lcov.info`
where `interfaces` is excluded folder and `bloc` are folders that should be still included

**Comment by xamantra** [comment]
@furaiev thanks for the suggestion. I'm not using bloc for my project.

But I was able to do it with my local fork. The code is currently dirty though. Might submit a pull request next week after I simplify my code.

**Comment by furaiev** [comment]
It's just an example.
You can use -r '.g.dart|.freezed.dart$|\bwidgets\b' for your widgets folder.

**Comment by xamantra** [comment]
@furaiev oh shit that worked. thanks!

only used `\bwidgets\b` regex. since I don't have any generated code in my project too.

`flutter pub run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '\bwidgets\b'`

deleting my fork and closing...
